services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: sales-agents-api
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-password}
      - GENERIC_TIMEZONE=America/Fortaleza
    volumes:
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
